source 'https://rubygems.org'

gem 'i18n', git: 'git@github.com:elpulgardelpanda/i18n.git', branch: 'dont-store-tr-for-locales-not-set-as-available'

# parseTree is dead, use this 3 instead for storing procs:
gem 'sourcify'
gem 'ruby_parser'
gem 'file-tail'

gem 'activerecord', '~> 3.x'
gem 'activesupport', '~> 3.x'
gem 'sqlite3'
gem 'mocha', '0.9.9'
gem 'test_declarative'
